service: sms-task
frameworkVersion: "3.28.1"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
        - sns:*
      Resource: "*"

resources:
  Resources:
    sqsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "sqsQueueOne"
        MaximumMessageSize: 1024
    snsTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "smsservice"

functions:
  hello:
    handler: src/lambdas/hello.handler
    events:
      - http:
          method: GET
          path: /any/method
  sendsqsmessage:
    handler: src/lambdas/sqs.sendMessage
    environment:
      SQS_QUEUE_URL: ${file(env.json):QUEUE_URL}
    events:
      - http:
          method: POST
          path: /sqs
  snsfromsqs:
    handler: src/lambdas/sns.sqsToSNS
    environment:
      SNS_TOPIC_ARN: ${file(env.json):SNS_TOPIC_ARN}
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-2:533322355632:sqsQueueOne
          batchSize: 1
